import { AiGateway } from './ai.gateway.js';
import { leadRepository } from '../leads/lead.repository.js';
import { AppError } from '../../shared/errors/AppError.js';
import { LeadModel } from '../leads/lead.model.js';

export class AiService {
  async generateLeadSummary(organizationId: string, userId: string, leadId: string) {
    const lead = await leadRepository.findById(organizationId, leadId);
    if (!lead) {
      throw AppError.notFound('Lead');
    }

    const prompt = `Analyze this sales lead and generate a structured JSON summary:\nName: ${lead.name}\nCompany: ${lead.company}\nStatus: ${lead.status}\nBudget: ${lead.budget}\nRequirement: ${lead.requirement || 'Not specified'}\nSource: ${lead.source}\nScore: ${lead.score}`;

    const result = await AiGateway.execute({
      organizationId,
      userId,
      feature: 'lead_summary',
      prompt,
      systemInstruction: 'You are an enterprise Sales CRM AI assistant. Return clean JSON only with fields: overview, intentLevel (HIGH/MEDIUM/LOW), suggestedAction, keyPoints (array). Do not include any other markdown formatting.',
    });

    let summaryData: {
      overview: string;
      intentLevel: 'HIGH' | 'MEDIUM' | 'LOW';
      suggestedAction: string;
      keyPoints: string[];
    };

    try {
      const text = result.output.trim();
      let parsed: any = null;

      // 1. Try direct parse
      try {
        parsed = JSON.parse(text);
      } catch {
        // 2. Strip code fences
        const unFenced = text
          .replace(/```(?:json)?\s*([\s\S]*?)\s*```/gi, '$1')
          .trim();
        try {
          parsed = JSON.parse(unFenced);
        } catch {
          // 3. Extract JSON object substring between { and }
          const firstBrace = text.indexOf('{');
          const lastBrace = text.lastIndexOf('}');
          if (firstBrace !== -1 && lastBrace !== -1 && lastBrace > firstBrace) {
            const candidate = text.substring(firstBrace, lastBrace + 1);
            parsed = JSON.parse(candidate);
          }
        }
      }

      if (parsed && typeof parsed === 'object') {
        const rawIntent = String(parsed.intentLevel || 'MEDIUM').toUpperCase();
        const intentLevel = (['HIGH', 'MEDIUM', 'LOW'].includes(rawIntent) ? rawIntent : 'MEDIUM') as 'HIGH' | 'MEDIUM' | 'LOW';

        summaryData = {
          overview: parsed.overview || parsed.summary || (typeof parsed === 'string' ? parsed : 'Lead analysis generated by AI.'),
          intentLevel,
          suggestedAction: parsed.suggestedAction || parsed.action || 'Schedule follow-up call with prospect',
          keyPoints: Array.isArray(parsed.keyPoints)
            ? parsed.keyPoints
            : typeof parsed.keyPoints === 'string'
            ? [parsed.keyPoints]
            : ['Inbound engagement detected'],
        };
      } else {
        throw new Error('Parsed output is not an object');
      }
    } catch {
      summaryData = {
        overview: result.output.replace(/[{}"[\]]/g, '').trim() || 'Qualified lead evaluating RevOps solutions.',
        intentLevel: 'MEDIUM',
        suggestedAction: 'Review requirement with lead',
        keyPoints: ['Inbound engagement detected'],
      };
    }

    // Save generated AI summary to Lead record
    await LeadModel.updateOne(
      { _id: leadId, organizationId },
      { $set: { aiSummary: { ...summaryData, isApproved: false } } }
    );

    return {
      aiSummary: summaryData,
      meta: {
        latencyMs: result.latencyMs,
        tokens: result.totalTokens,
        model: result.model,
      },
    };
  }

  async generateEmailDraft(
    organizationId: string,
    userId: string,
    data: { recipientName: string; context: string; goal: string }
  ) {
    const prompt = `Write a professional, high-converting sales outreach email:\nRecipient: ${data.recipientName}\nGoal: ${data.goal}\nContext: ${data.context}`;

    const result = await AiGateway.execute({
      organizationId,
      userId,
      feature: 'email_draft',
      prompt,
      systemInstruction: 'You are an expert sales representative. Write concise, polite, and persuasive emails.',
    });

    return {
      draft: result.output,
      meta: {
        latencyMs: result.latencyMs,
        tokens: result.totalTokens,
        model: result.model,
      },
    };
  }
}

export const aiService = new AiService();
