import { Lead, Deal, CallRecord, ActivityEvent, Task, Proposal, Invoice, MessageThread } from '@/types';

export const SEED_LEADS: Lead[] = [
  {
    id: 'lead_01',
    organizationId: 'org_acme_corp',
    name: 'Sarah Jenkins',
    title: 'VP of Engineering',
    company: 'Apex Capital Logistics',
    email: 's.jenkins@apexlogistics.io',
    phone: '+1 (415) 890-2134',
    status: 'QUALIFIED',
    score: 94,
    scoreCategory: 'HOT',
    assignedTo: { id: 'usr_rep_01', name: 'Devon Patel' },
    source: 'INBOUND_CALL',
    estimatedValue: 120000,
    lastContactedAt: '2 hours ago',
    createdAt: '2026-08-14T09:30:00Z',
    aiSummary: {
      overview: 'High purchasing intent. Urgent need to replace legacy CRM with multi-channel WhatsApp and voice pipeline automation before Q4 kickoff.',
      intentLevel: 'HIGH',
      suggestedAction: 'Schedule technical architecture review and propose Enterprise tier quote.',
      keyPoints: [
        '50+ seat rollout across North America',
        'Budget signed off by CTO and Finance Controller',
        'Requested SOC2 and custom SLA terms',
      ],
      isApproved: true,
    },
  },
  {
    id: 'lead_02',
    organizationId: 'org_acme_corp',
    name: 'Rajesh Subramaniam',
    title: 'Head of Global Sales Ops',
    company: 'FinVerve Technologies',
    email: 'rajesh.s@finverve.com',
    phone: '+1 (650) 412-9988',
    status: 'CONTACTED',
    score: 86,
    scoreCategory: 'HOT',
    assignedTo: { id: 'usr_rep_01', name: 'Devon Patel' },
    source: 'LINKEDIN',
    estimatedValue: 85000,
    lastContactedAt: 'Yesterday',
    createdAt: '2026-08-12T14:15:00Z',
    aiSummary: {
      overview: 'Exploring telecaller autodialer and real-time SLA breach monitoring. Currently testing competitor trial.',
      intentLevel: 'HIGH',
      suggestedAction: 'Send comparison breakdown highlighting sub-second latency and zero-trust permissions.',
      keyPoints: [
        'Evaluating 3 vendors',
        'Key blocker: Telecaller queue performance and latency',
      ],
    },
  },
  {
    id: 'lead_03',
    organizationId: 'org_acme_corp',
    name: 'Evelyn St. Claire',
    title: 'Chief Revenue Officer',
    company: 'BlueHarbor Medical Health',
    email: 'e.stclaire@blueharbor.org',
    phone: '+1 (212) 765-4321',
    status: 'NEW',
    score: 62,
    scoreCategory: 'WARM',
    assignedTo: { id: 'usr_sdr_01', name: 'Jordan Miller' },
    source: 'WEBSITE',
    estimatedValue: 195000,
    lastContactedAt: '3 days ago',
    createdAt: '2026-08-11T11:00:00Z',
    aiSummary: {
      overview: 'Downloaded enterprise whitepaper on automated revenue operations. Inbound form completed.',
      intentLevel: 'MEDIUM',
      suggestedAction: 'Qualify HIPAA compliance requirements via SDR intro call.',
      keyPoints: [
        'Medical compliance priority',
        'Estimated team size: 120 reps',
      ],
    },
  },
  {
    id: 'lead_04',
    organizationId: 'org_acme_corp',
    name: 'Michael Vance Jr.',
    title: 'Director of Business Development',
    company: 'Quantum Dynamics Corp',
    email: 'mvance@quantum-dyn.com',
    phone: '+1 (312) 555-0199',
    status: 'NURTURING',
    score: 45,
    scoreCategory: 'COLD',
    assignedTo: { id: 'usr_rep_01', name: 'Devon Patel' },
    source: 'META_ADS',
    estimatedValue: 45000,
    lastContactedAt: '1 week ago',
    createdAt: '2026-08-05T16:20:00Z',
    aiSummary: {
      overview: 'Requested roadmap update for custom webhook triggers. Not ready for immediate deal closing.',
      intentLevel: 'LOW',
      suggestedAction: 'Enroll in monthly product webinar nurture sequence.',
      keyPoints: [
        'Evaluation deferred to next fiscal year',
      ],
    },
  },
  {
    id: 'lead_05',
    organizationId: 'org_acme_corp',
    name: 'Chloe Tremblay',
    title: 'Founder & CEO',
    company: 'Nordic AI Solutions',
    email: 'chloe@nordicai.io',
    phone: '+1 (514) 909-3321',
    status: 'NEW',
    score: 91,
    scoreCategory: 'HOT',
    assignedTo: { id: 'usr_tele_01', name: 'Elena Rostova' },
    source: 'REFERRAL',
    estimatedValue: 110000,
    lastContactedAt: 'Just now',
    createdAt: '2026-08-16T08:00:00Z',
    aiSummary: {
      overview: 'Referral from existing partner. Urgent need for automated proposal generator and Stripe invoicing.',
      intentLevel: 'HIGH',
      suggestedAction: 'Execute immediate Telecaller phone discovery.',
      keyPoints: ['High growth seed round closed', 'Ready to onboard in 7 days'],
    },
  }
];

export const SEED_DEALS: Deal[] = [
  {
    id: 'deal_01',
    organizationId: 'org_acme_corp',
    title: 'Enterprise CRM Overhaul — Apex Capital',
    company: 'Apex Capital Logistics',
    contactName: 'Sarah Jenkins',
    value: 120000,
    stage: 'NEGOTIATION',
    probability: 85,
    expectedCloseDate: '2026-08-30',
    assignedTo: { id: 'usr_rep_01', name: 'Devon Patel' },
    health: 'HEALTHY',
    createdAt: '2026-08-01',
    updatedAt: '2026-08-15',
  },
  {
    id: 'deal_02',
    organizationId: 'org_acme_corp',
    title: 'SalesOps Autodialer Integration',
    company: 'FinVerve Technologies',
    contactName: 'Rajesh Subramaniam',
    value: 85000,
    stage: 'PROPOSAL',
    probability: 70,
    expectedCloseDate: '2026-09-15',
    assignedTo: { id: 'usr_rep_01', name: 'Devon Patel' },
    health: 'HEALTHY',
    createdAt: '2026-08-05',
    updatedAt: '2026-08-14',
  },
  {
    id: 'deal_03',
    organizationId: 'org_acme_corp',
    title: 'Hospital Network Telephony Suite',
    company: 'BlueHarbor Medical Health',
    contactName: 'Evelyn St. Claire',
    value: 195000,
    stage: 'QUALIFICATION',
    probability: 40,
    expectedCloseDate: '2026-10-01',
    assignedTo: { id: 'usr_sdr_01', name: 'Jordan Miller' },
    health: 'AT_RISK',
    createdAt: '2026-08-10',
    updatedAt: '2026-08-13',
  },
  {
    id: 'deal_04',
    organizationId: 'org_acme_corp',
    title: 'Nordic AI Core Platform Licensing',
    company: 'Nordic AI Solutions',
    contactName: 'Chloe Tremblay',
    value: 110000,
    stage: 'DISCOVERY',
    probability: 60,
    expectedCloseDate: '2026-09-01',
    assignedTo: { id: 'usr_rep_01', name: 'Devon Patel' },
    health: 'HEALTHY',
    createdAt: '2026-08-15',
    updatedAt: '2026-08-16',
  },
  {
    id: 'deal_05',
    organizationId: 'org_acme_corp',
    title: 'CyberShield 100-Seat Expansion',
    company: 'CyberShield Global',
    contactName: 'David Thorne',
    value: 240000,
    stage: 'WON',
    probability: 100,
    expectedCloseDate: '2026-08-10',
    assignedTo: { id: 'usr_rep_01', name: 'Devon Patel' },
    health: 'HEALTHY',
    createdAt: '2026-07-20',
    updatedAt: '2026-08-10',
  }
];

export const SEED_CALLS: CallRecord[] = [
  {
    id: 'call_01',
    organizationId: 'org_acme_corp',
    leadId: 'lead_01',
    leadName: 'Sarah Jenkins',
    leadPhone: '+1 (415) 890-2134',
    leadCompany: 'Apex Capital Logistics',
    callerId: 'usr_rep_01',
    callerName: 'Devon Patel',
    status: 'COMPLETED',
    disposition: 'MEETING_BOOKED',
    durationSeconds: 432,
    aiSentiment: 'POSITIVE',
    transcriptSnippet: "Sarah: 'Our current tool is dropping calls during peak hours. If ADVMEN can guarantee 99.99% uptime, we are ready to move forward this quarter.'",
    notes: 'Booked executive demo for Thursday 2 PM. Verified security team will attend.',
    completedAt: '2 hours ago',
  },
  {
    id: 'call_02',
    organizationId: 'org_acme_corp',
    leadId: 'lead_05',
    leadName: 'Chloe Tremblay',
    leadPhone: '+1 (514) 909-3321',
    leadCompany: 'Nordic AI Solutions',
    callerId: 'usr_tele_01',
    callerName: 'Elena Rostova',
    status: 'QUEUED',
    durationSeconds: 0,
    scheduledAt: 'Next in Queue',
  },
  {
    id: 'call_03',
    organizationId: 'org_acme_corp',
    leadId: 'lead_02',
    leadName: 'Rajesh Subramaniam',
    leadPhone: '+1 (650) 412-9988',
    leadCompany: 'FinVerve Technologies',
    callerId: 'usr_rep_01',
    callerName: 'Devon Patel',
    status: 'COMPLETED',
    disposition: 'INTERESTED',
    durationSeconds: 310,
    aiSentiment: 'POSITIVE',
    transcriptSnippet: "Rajesh confirmed budget is allocated. Requested custom proposal draft with volume discount.",
    notes: 'Send Proposal v1 today.',
    completedAt: 'Yesterday',
  }
];

export const SEED_ACTIVITIES: ActivityEvent[] = [
  {
    id: 'act_01',
    type: 'CALL',
    title: 'Outbound Discovery Call Completed',
    description: 'Call connected for 7m 12s. Positive sentiment detected by AI Copilot. Stage updated to Negotiation.',
    actorName: 'Devon Patel',
    timestamp: 'Today at 10:45 AM',
  },
  {
    id: 'act_02',
    type: 'AI_INSIGHT',
    title: 'AI Buying Signal Detected',
    description: 'Lead visited Enterprise Pricing page 4 times in the past 24 hours. Lead score increased from 82 to 94.',
    actorName: 'ADVMEN AI Agent',
    timestamp: 'Today at 08:30 AM',
  },
  {
    id: 'act_03',
    type: 'WHATSAPP',
    title: 'WhatsApp Follow-up Sent',
    description: 'Sent security architecture whitepaper and SOC2 Type II compliance audit packet.',
    actorName: 'Devon Patel',
    timestamp: 'Yesterday at 04:15 PM',
  },
  {
    id: 'act_04',
    type: 'STAGE_CHANGE',
    title: 'Stage Changed to Negotiation',
    description: 'Moved from Proposal stage after receiving verbal sign-off from VP of Engineering.',
    actorName: 'Devon Patel',
    timestamp: 'Yesterday at 02:00 PM',
  }
];

export const SEED_TASKS: Task[] = [
  {
    id: 'task_01',
    organizationId: 'org_acme_corp',
    title: 'Submit Enterprise SLA Draft to Legal',
    dueDate: 'Today (Urgent)',
    isOverdue: false,
    isCompleted: false,
    priority: 'URGENT',
    relatedTo: { type: 'DEAL', id: 'deal_01', name: 'Apex Capital Overhaul' },
    assignedToName: 'Devon Patel',
    slaBreachInMinutes: 45,
  },
  {
    id: 'task_02',
    organizationId: 'org_acme_corp',
    title: 'Send Custom Proposal to Rajesh Subramaniam',
    dueDate: 'Today at 5:00 PM',
    isOverdue: false,
    isCompleted: false,
    priority: 'HIGH',
    relatedTo: { type: 'DEAL', id: 'deal_02', name: 'FinVerve Autodialer' },
    assignedToName: 'Devon Patel',
  },
  {
    id: 'task_03',
    organizationId: 'org_acme_corp',
    title: 'Speed Dial Outreach for Inbound Web Form Leads',
    dueDate: 'Completed',
    isOverdue: false,
    isCompleted: true,
    priority: 'MEDIUM',
    relatedTo: { type: 'LEAD', id: 'lead_05', name: 'Chloe Tremblay' },
    assignedToName: 'Elena Rostova',
  }
];

export const SEED_PROPOSALS: Proposal[] = [
  {
    id: 'prop_01',
    proposalNumber: 'PROP-2026-089',
    dealId: 'deal_01',
    dealTitle: 'Enterprise CRM Overhaul',
    company: 'Apex Capital Logistics',
    recipientName: 'Sarah Jenkins',
    recipientEmail: 's.jenkins@apexlogistics.io',
    amount: 120000,
    status: 'VIEWED',
    validUntil: '2026-09-30',
    createdAt: '2026-08-14',
  },
  {
    id: 'prop_02',
    proposalNumber: 'PROP-2026-084',
    dealId: 'deal_02',
    dealTitle: 'SalesOps Autodialer Integration',
    company: 'FinVerve Technologies',
    recipientName: 'Rajesh Subramaniam',
    recipientEmail: 'rajesh.s@finverve.com',
    amount: 85000,
    status: 'DRAFT',
    validUntil: '2026-09-15',
    createdAt: '2026-08-15',
  }
];

export const SEED_INVOICES: Invoice[] = [
  {
    id: 'inv_01',
    invoiceNumber: 'INV-2026-4421',
    company: 'CyberShield Global',
    amount: 240000,
    currency: 'USD',
    status: 'PAID',
    dueDate: '2026-08-15',
    paidAt: '2026-08-10',
    createdAt: '2026-07-28',
  },
  {
    id: 'inv_02',
    invoiceNumber: 'INV-2026-4489',
    company: 'Apex Capital Logistics',
    amount: 36000,
    currency: 'USD',
    status: 'SENT',
    dueDate: '2026-09-01',
    createdAt: '2026-08-15',
  },
  {
    id: 'inv_03',
    invoiceNumber: 'INV-2026-4410',
    company: 'Quantum Dynamics Corp',
    amount: 12500,
    currency: 'USD',
    status: 'OVERDUE',
    dueDate: '2026-08-01',
    createdAt: '2026-07-15',
  }
];

export const SEED_MESSAGES: MessageThread[] = [
  {
    id: 'thread_01',
    contactName: 'Sarah Jenkins',
    contactChannel: 'WHATSAPP',
    contactAddress: '+1 (415) 890-2134',
    lastMessageSnippet: 'Can you also send over the SLA breach alert webhook specs?',
    unreadCount: 1,
    lastMessageAt: '12m ago',
    messages: [
      { id: 'm1', sender: 'CONTACT', content: 'Hi Devon, thanks for the call earlier today.', timestamp: '10:45 AM', status: 'READ' },
      { id: 'm2', sender: 'USER', content: 'Glad to connect, Sarah! Sending over the proposal packet now.', timestamp: '10:47 AM', status: 'READ' },
      { id: 'm3', sender: 'CONTACT', content: 'Can you also send over the SLA breach alert webhook specs?', timestamp: '11:15 AM', status: 'DELIVERED' },
      { id: 'm4', sender: 'AI_DRAFT', content: 'Draft reply: Hi Sarah, absolutely! ADVMEN supports sub-second webhook triggers for SLA risk and breach events. Here is the direct developer documentation link: https://docs.advmen.io/webhooks/sla', timestamp: '11:16 AM', status: 'SUGGESTED' }
    ]
  },
  {
    id: 'thread_02',
    contactName: 'Rajesh Subramaniam',
    contactChannel: 'EMAIL',
    contactAddress: 'rajesh.s@finverve.com',
    lastMessageSnippet: 'Reviewed the proposal draft with our operations team.',
    unreadCount: 0,
    lastMessageAt: '2h ago',
    messages: [
      { id: 'm21', sender: 'CONTACT', content: 'Reviewed the proposal draft with our operations team. Looking forward to our demo.', timestamp: '09:30 AM', status: 'READ' }
    ]
  }
];
